package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller // This means that this class is a REST Controller with default @ResponseBody annotation
@CrossOrigin(origins = "http://localhost:4200", methods = { RequestMethod.GET, RequestMethod.POST, RequestMethod.PUT,
		RequestMethod.DELETE, RequestMethod.OPTIONS })
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired 
	private UserRepository userRepository;

	@RequestMapping("/demo")
	public String index() {
		String indexView = "test/browser/index.html";
		return indexView;
	}
	
	@PostMapping(path = "/add")
	public @ResponseBody String addNewUser(@ModelAttribute User user) {
		// @RequestParam means it is a parameter from the GET or POST request
		// @ResponseBody means the returned String is the response, not a view name
		userRepository.save(user);
		return "{\"message\": \"successfully!\"}"; // Return a view name
	}

	@PutMapping(path = "/modify")
	public @ResponseBody String modifyUser(@ModelAttribute User user) {
		userRepository.save(user);
		return "{\"message\": \"successfully!\"}"; // Return a view name
	}

	@DeleteMapping(path = "/delete/{id}")
	public @ResponseBody String removeUser(@PathVariable int id) {
		userRepository.deleteById(id);
		return "{\"message\": \"successfully!\"}"; // Return a view name
	}

	@GetMapping(path = "/getAll")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
